#!/bin/sh

rsync -av ../ax_webclient/lib         \
          ../ax_webclient/assets      \
          ../ax_webclient/priv        \
          ../ax_webclient/README.md   \
          ../ax_webclient/config      \
          ../ax_webclient/mix.exs     \
          ../ax_webclient/test        \
          ./


