#!/bin/sh

awssh docker ps | grep altex

cd altex_iboard_cc \
  && docker build . $* -t altex_iboard_cc \
  && docker tag altex_iboard_cc iboard/altex_iboard_cc:latest \
  && docker push iboard/altex_iboard_cc:latest \
  && cd -

awssh /home/ec2-user/iboard.cc/upgrade-altex
awssh docker ps | grep altex
