#!/bin/sh

PREFIX="ax"

if [ "x$1" = "x" ]; then
  DIRECTORY=`pwd`
else
  DIRECTORY=$1
fi

MIX_PROJECTS="`ls -1d ${DIRECTORY}/${PREFIX}*` ${DIRECTORY}/state_server"

for PROJECT in ${MIX_PROJECTS}; do

  echo "======> ${PROJECT}"
  cd ${PROJECT} && git status | grep "^Your" && cd - >/dev/null
  echo ""

done

