#!/bin/sh

PREFIX="ax"

if [ "x$1" = "x" ]; then
  DIRECTORY=`pwd`
else
  DIRECTORY=$1
fi

MIX_PROJECTS="`ls -1d ${DIRECTORY}/${PREFIX}*` ${DIRECTORY}/state_server"

RESULTS=""
for PROJECT in ${MIX_PROJECTS}; do

  echo "======> ${PROJECT}"
  cd ${PROJECT} && mix test | grep "test" && cd -
  RESULTS="${RESULTS}$? ${PROJECT}\n"
  echo ""

done

echo "AX-TEST RESULTS"
echo "---------------"
echo "${RESULTS}" | sed "s/0/PASSED/g" | sed "s/1/FAILED/g"
